### ISSUE TITLE
"Login temporarily failed"

### ISSUE THREAD

**Issue by matthazinski** [tatosaurus/snapy#10]
Just started getting this error this morning:

```
    Exception: Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)
```

Related: https://github.com/mgp25/SC-API/issues/184

**Comment by matthazinski** [comment]
Looks like it's fixed in https://github.com/mgp25/SC-API/commit/b6576561ca2ae40ac5b72ac33c5339de65815780 if anyone wants to port it to Python.

**Comment by beeramtheman** [comment]
@matthazinski https://github.com/rxw/snapy/pull/14
