### ISSUE TITLE
Error messages when casper is down

### ISSUE THREAD

**Issue by erikhazzard** [tatosaurus/snapy#18]
Hello, thanks for the great library. 

When casper.io is down, a KeyError is thrown when attempting to login:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/snapy/__init__.py", line 176, in login
KeyError: 'signature'
```

The response of `get_client_auth_token` is `{u'message': u'Signing Service Unavailable', u'code': 503}`. 

It would be useful to catch it when the casper API is down and throw a more semantic error.
Thanks for the library!

**Comment by rxw** [comment]
I will see what I can do, thanks for your feedback!
