### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by nzraad** [tatosaurus/snapy#25]
Can you guys explain what to do? So, I got the file and opened it and changed the line with the casper key and all that other username stuff. But then i also did the python setup.py install command, but what do you do then? I am so confused! :) Please help much appreciated! Also if you know of a way that I can run this script on a web server so I don't have to keep my laptop always on, that would be amazing also! If you want to talk in a different method feel free to Direct Message me on Twitter @insanedoughnut

**Comment by Chiggins** [comment]
After installing the library using `python setup.py install`, you'll then create a new Python file to utilize the library.

```
from snapy import Snapchat

s = Snapchat()
s.login("username", "password", "gmail@gmail.com", "pass@gmail.com", "casper_key", "casper_secret")
snaps = s.get_snaps()
```

That is an extremely basic script, but you'll get the point from there. As for running it on a web server, you'll want to utilize a [cron job](http://www.unixgeeks.org/security/newbie/unix/cron-1.html).
