### ISSUE TITLE
s.login() suddenly doesn't work due to base64 problem?

### ISSUE THREAD

**Issue by Bassir** [tatosaurus/snapy#26]
All of a sudden, my script utilizing Snapy is outputting the following error.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "build/bdist.macosx-10.11-intel/egg/snapy/**init**.py", line 175, in login
>   File "build/bdist.macosx-10.11-intel/egg/snapy/API.py", line 37, in getSnapchatAttestation
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 76, in b64decode
>     raise TypeError(msg)
> TypeError: Incorrect padding

Could something have changed with the APIs utilized by Casper or Snapy?

**Comment by Chiggins** [comment]
The Casper API is currently down and being worked on. Look up the page
"Casper App" on Facebook for more news and updates.
