### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by khantext** [tatosaurus/snapy#29]
The README.md appears to have a broken link.

It states, "You will need to set this data in the constructor, as shown in the _examples_." The "examples" is a hyperlink (https://github.com/rxw/snapy/blob/master/examples) which leads to a 404 error.

**Comment by khantext** [comment]
And what exactly is the _constructor_ that is referenced here? The word "constructor" only appears once in this repository, in this README file.

I have a set of Casper API keys, but I am uncertain how to use them in concert with this Python module.

**Comment by rxw** [comment]
Sorry about that, the way in which you utilize the Casper API is by passing it as the parameters to the login method of the Snapchat object as ckey (Casper key) and csecret (Casper secret). A quick overview of this method will probably make it clearer for you. Regarding the readme, the word constructor appears to be a mistake while adapting the solution from a PHP library. I will fix this as soon as I get home. Thanks for your feedback.
