### ISSUE TITLE
Attestation Service unavailable?

### ISSUE THREAD

**Issue by khantext** [tatosaurus/snapy#30]
I finally have what seems to be a well-constructed .login method with valid credentials. On my first attempt, I received this, and I'm uncertain what to make of it.

`Traceback (most recent call last):
  File "snapchat.py", line 78, in <module>
    main()
  File "snapchat.py", line 31, in main
    s.login(username, userpassword, gmail, gpasswd, casper_api_key, casper_api_secret)
  File "build/bdist.linux-x86_64/egg/snapy/__init__.py", line 175, in login
  File "build/bdist.linux-x86_64/egg/snapy/API.py", line 32, in getSnapchatAttestation
  File "build/bdist.linux-x86_64/egg/snapy/Agent.py", line 15, in get
  File "build/bdist.linux-x86_64/egg/snapy/Agent.py", line 47, in request
snapy.Exception.CasperException: API Response: [404] The Attestation Service is no longer available.`

Has anybody else seen this before? Any ideas on how to proceed?

**Comment by Chiggins** [comment]
This repo is out of date and will really only work if you have auth_tokens
that were generated a few months ago. You'll want to check out the Casper
Developer console for being able to login and such, but it does cost money.
https://developers.casper.io

**Comment by khantext** [comment]
I have paid the subscription fee for the Casper API, and I have a set of valid API keys. I have included those keys in the Snapchat login method.

Are the credentials actually just hard-coded in this function? Are my own new/fresh API keys possibly being ignored?

**Comment by Chiggins** [comment]
Ah right on. I still think this repo needs updating to work with the new Casper API model. I don't have the money to pay for API keys to get this repo working but if @liamcottle doesn't mind generating me some free keys I'd get this up and running ;)

**Comment by khantext** [comment]
Chiggins, I can temporarily loan you an API key if you're able and interested in fixing up this repo.

**Comment by Bassir** [comment]
@Chiggins can you still use an auth token generated by the Android Casper app?

**Comment by Chiggins** [comment]
Nope, doesn't work. At least not last I tried.

**Comment by Bassir** [comment]
@Chiggins Well, I guess we just have to wait for @liamcottle to finish his cheaper username-based access service.
