### ISSUE TITLE
Unsupported Snapchat/OS version

### ISSUE THREAD

**Issue by matthazinski** [tatosaurus/snapy#4]
Exception: You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!

**Comment by Chiggins** [comment]
Just got that on mine as well.

**Comment by Chiggins** [comment]
I would recommend looking at this commit that seems to fix it https://github.com/mgp25/SC-API/commit/fc02c6b8449afe1e418f2e048bfca3ba26fc7922

**Comment by matthazinski** [comment]
I implemented what SC-API did here: https://github.com/matthazinski/snapy/commit/b32b9f4a90fb69f9344946d16426cd003e646120

They're sending client credentials over plain HTTP to http://casper.io though so I wouldn't recommend using it.

**Comment by Chiggins** [comment]
Well, Casper is an Android app that works well. Does that URL work with
https?

**Comment by rxw** [comment]
I think I'll implement it until i figure out a better way of doing it.
Thanks for your help! - tato

**Comment by matthazinski** [comment]
Nope, it's HTTP-only.
