### ISSUE TITLE
"Invalid gmail address" error

### ISSUE THREAD

**Issue by beeramtheman** [tatosaurus/snapy#6]
What are the requirements of a gmail account to work with Snapy?

When I use my real gmail email and password I get an "Invalid gmail
address" error.

**Comment by rxw** [comment]
It should work if you're using the correct credentials. However Google can block snapy from accessing your account if it recognized your IP address as being a server or vpn. I'd recommend making a new one and trying with that one. Make sure you're not using a vpn or trying it from a server.
